# Class 102 Reading Notes

These are my Day 1 notes about markdown:

 - Markdown utilizes basic and extended syntax elements to cover most of the necessary test-formatting needs. If you use Markdown long enough, you’ll inevitably discover that it doesn’t support something you are working on. 

 - Tabs and whitespace have a special meaning in Markdown. You can use trailing whitespace to create line breaks, and you can use tabs to create code blocks. iA Writer allows you to customize indentation settings for the editor in the application preferences.

 - Markdown doesn’t allow you to change the color of text, but if your Markdown processor supports HTML, you can use the <font> HTML tag. The color attribute allows you to specify the font color using a color’s name or the hexadecimal #RRGGBB code.
  
 - The Markdown syntax for images doesn’t allow you to specify the width and height of images. If you need to resize an image and your Markdown processor supports HTML, you can use the img HTML tag with the width and height attributes to set the dimensions of an image in pixels.
  
  [https://codylobdell.github.io/reading-notes/](https://codylobdell.github.io/reading-notes/ClassOneNotes)
